# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 896)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(10, 150, 1111, 701))
        self.file_list.setObjectName("file_list")
        self.search_file_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_file_line_edit.setGeometry(QtCore.QRect(140, 30, 981, 31))
        self.search_file_line_edit.setObjectName("search_file_line_edit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 371, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.add_file_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.add_file_pushButton.setGeometry(QtCore.QRect(0, 30, 131, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_file_pushButton.setIcon(icon)
        self.add_file_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.add_file_pushButton.setObjectName("add_file_pushButton")
        self.searc_keyword_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searc_keyword_lineEdit.setGeometry(QtCore.QRect(140, 90, 181, 31))
        self.searc_keyword_lineEdit.setObjectName("searc_keyword_lineEdit")
        self.edited_date_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.edited_date_comboBox.setGeometry(QtCore.QRect(340, 90, 181, 31))
        self.edited_date_comboBox.setCurrentText("")
        self.edited_date_comboBox.setObjectName("edited_date_comboBox")
        self.file_type_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.file_type_comboBox.setGeometry(QtCore.QRect(540, 90, 191, 31))
        self.file_type_comboBox.setObjectName("file_type_comboBox")
        self.owner_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.owner_comboBox.setGeometry(QtCore.QRect(750, 90, 191, 31))
        self.owner_comboBox.setObjectName("owner_comboBox")
        self.edit_date_label = QtWidgets.QLabel(self.centralwidget)
        self.edit_date_label.setGeometry(QtCore.QRect(340, 70, 171, 16))
        self.edit_date_label.setObjectName("edit_date_label")
        self.file_type_label = QtWidgets.QLabel(self.centralwidget)
        self.file_type_label.setGeometry(QtCore.QRect(540, 70, 171, 16))
        self.file_type_label.setObjectName("file_type_label")
        self.owner_label = QtWidgets.QLabel(self.centralwidget)
        self.owner_label.setGeometry(QtCore.QRect(750, 70, 171, 16))
        self.owner_label.setObjectName("owner_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "file_window"))
        self.search_file_line_edit.setText(_translate("MainWindow", "Search A File:"))
        self.add_file_pushButton.setText(_translate("MainWindow", "Add File"))
        self.searc_keyword_lineEdit.setText(_translate("MainWindow", "Search Keyword"))
        self.edit_date_label.setText(_translate("MainWindow", "Edited Date:"))
        self.file_type_label.setText(_translate("MainWindow", "File Type:"))
        self.owner_label.setText(_translate("MainWindow", "Owner:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
