# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogInOrRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from LogIn import Ui_LogInWindow
from Register import Ui_RegisterWindow


class Ui_LogInOrRegister(object):
    def OpenLogInWindow(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LogInWindow()
        self.ui.setupUi(self.window, MainWindow)
        self.window.show()
        MainWindow.close()

    def OpenRegistrtWindow(self, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RegisterWindow()
        self.ui.setupUi(self.window, MainWindow)
        self.window.show()
        MainWindow.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 609)
        MainWindow.setStyleSheet("background-color: rgb(236, 243, 244);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogInButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.OpenLogInWindow(MainWindow))
        self.LogInButton.setGeometry(QtCore.QRect(280, 300, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LogInButton.setFont(font)
        self.LogInButton.setStyleSheet("QPushButton{\n"
"background-color: #43BEF7;\n"
"border-radius: 15px;\n"
"border-bottom: 2px solid;\n"
"border-right: 2px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4385F7;\n"
"}")
        self.LogInButton.setObjectName("pushButton_2")
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.OpenRegistrtWindow(MainWindow))
        self.RegisterButton.setGeometry(QtCore.QRect(280, 180, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setStyleSheet("QPushButton{\n"
"background-color: #43BEF7;\n"
"border-radius: 15px;\n"
"border-bottom: 2px solid;\n"
"border-right: 2px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4385F7;\n"
"}")
        self.RegisterButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "logInOrRegister"))
        self.LogInButton.setText(_translate("MainWindow", "Log In"))
        self.RegisterButton.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "Välkommen till python-projekt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LogInOrRegister()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
